apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: worker-node-cpu-capacity
spec:
  columns:
    - name: period_start
      type: timestamp
      unit: date
    - name: period_end
      type: timestamp
      unit: date
    - name: node
      type: varchar
      unit: kubernetes_node
    - name: resource_id
      type: varchar
    - name: node_capacity_cpu_core_seconds
      type: double
      unit: cpu_core_seconds
  inputs:
    - name: ReportingStart
      type: time
    - name: ReportingEnd
      type: time
    - default: worker-node-cpu-capacity-raw
      name: WorkerNodeCpuCapacityRawDataSourceName
      type: ReportDataSource
  query: >
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart| prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
      node,
      resource_id,
      sum(node_capacity_cpu_core_seconds) as node_capacity_cpu_core_seconds
    FROM {| dataSourceTableName .Report.Inputs.WorkerNodeCpuCapacityRawDataSourceName
    |}

    WHERE "timestamp" >= timestamp '{| default .Report.ReportingStart
    .Report.Inputs.ReportingStart | prestoTimestamp |}'

    AND "timestamp" < timestamp '{| default .Report.ReportingEnd
    .Report.Inputs.ReportingEnd | prestoTimestamp |}'

    AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart |
    prometheusMetricPartitionFormat |}'

    AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd |
    prometheusMetricPartitionFormat |}'

    GROUP BY node, resource_id
