apiVersion: metering.openshift.io/v1
kind: ReportQuery
metadata:
  name: cluster-worker-cpu-capacity
spec:
  columns:
    - name: period_start
      type: timestamp
      unit: date
    - name: period_end
      type: timestamp
      unit: date
    - name: total_cluster_capacity_cpu_core_seconds
      type: double
      unit: cpu_core_seconds
    - name: avg_cluster_capacity_cpu_cores
      type: double
      unit: cpu_cores
    - name: avg_node_count
      type: double
  inputs:
    - name: ReportingStart
      type: time
    - name: ReportingEnd
      type: time
    - name: ClusterWorkerCpuCapacityReportName
      type: Report
    - default: cluster-worker-cpu-capacity-raw
      name: ClusterWorkerCpuCapacityRawDataSourceName
      type: ReportDataSource
  query: |
    SELECT
      timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}' AS period_start,
      timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}' AS period_end,
    {|- if .Report.Inputs.ClusterWorkerCpuCapacityReportName |}
      sum(total_cluster_capacity_cpu_core_seconds) as total_cluster_capacity_cpu_core_seconds,
      avg(avg_cluster_capacity_cpu_cores) as avg_cluster_capacity_cpu_cores,
      avg(avg_node_count) AS avg_node_count
      FROM {| .Report.Inputs.ClusterWorkerCpuCapacityReportName | reportTableName |}
      WHERE period_start  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
      AND period_end <= timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
    {|- else |}
      sum(cpu_core_seconds)  as total_cluster_capacity_cpu_core_seconds,
      avg(cpu_cores) as avg_cluster_capacity_cpu_cores,
      avg(node_count) AS avg_node_count
      FROM {| dataSourceTableName .Report.Inputs.ClusterWorkerCpuCapacityRawDataSourceName |}
      WHERE "timestamp"  >= timestamp '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prestoTimestamp |}'
      AND "timestamp" < timestamp '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prestoTimestamp |}'
      AND dt >= '{| default .Report.ReportingStart .Report.Inputs.ReportingStart | prometheusMetricPartitionFormat |}'
      AND dt <= '{| default .Report.ReportingEnd .Report.Inputs.ReportingEnd | prometheusMetricPartitionFormat |}'
    {|- end |}
